apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  tuningOptions: {}
  unsupportedConfigOverrides: null
  replicas: 3
