apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  disableNameSuffixHash: true

resources:
  - default-ingresscontroller.yaml
  - ingresses-config.yaml
